# Generated by Django 3.2.16 on 2023-04-19 09:27

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_Settings',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('from_account', models.CharField(max_length=80, null=True)),
                ('to_account', models.CharField(max_length=80, null=True)),
                ('mention_account', models.TextField(null=True)),
                ('hashtag', models.CharField(max_length=80, null=True)),
                ('until', models.DateTimeField(default=django.utils.timezone.now)),
                ('since', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 9, 27, 47, 285417, tzinfo=utc))),
                ('interval', models.IntegerField(default=1)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('headless', models.BooleanField(default=True)),
                ('limit', models.IntegerField()),
                ('display_type', models.CharField(default='Latest', max_length=30)),
                ('resume', models.CharField(max_length=100)),
                ('proxy', models.CharField(max_length=20)),
                ('proximity', models.CharField(max_length=20)),
                ('geocode', models.CharField(max_length=100)),
                ('minreplies', models.IntegerField()),
                ('minlikes', models.IntegerField()),
                ('minretweets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='D_Settings',
            fields=[
                ('D_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('from_account', models.CharField(max_length=80, null=True)),
                ('to_account', models.CharField(max_length=80, null=True)),
                ('mention_account', models.TextField(null=True)),
                ('hashtag', models.CharField(max_length=80, null=True)),
                ('until', models.DateTimeField(default=django.utils.timezone.now)),
                ('since', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 9, 27, 47, 214047, tzinfo=utc))),
                ('interval', models.IntegerField(default=1)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('headless', models.BooleanField(default=True)),
                ('limit', models.IntegerField()),
                ('display_type', models.CharField(default='Latest', max_length=30)),
                ('resume', models.CharField(max_length=80)),
                ('proxy', models.CharField(max_length=20)),
                ('proximity', models.CharField(max_length=20)),
                ('geocode', models.CharField(max_length=80)),
                ('minreplies', models.IntegerField()),
                ('minlikes', models.IntegerField()),
                ('minretweets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result_Output',
            fields=[
                ('R_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('FileName', models.CharField(default=None, max_length=100)),
                ('UserScreenName', models.CharField(max_length=100, null=True)),
                ('UserName', models.CharField(max_length=100, null=True)),
                ('Timestamp', models.DateTimeField()),
                ('Text', models.TextField()),
                ('Embedded_text', models.TextField()),
                ('Emojis', models.CharField(max_length=100)),
                ('Comments', models.TextField()),
                ('Likes', models.IntegerField()),
                ('Retweets', models.IntegerField()),
                ('Imag_link', models.CharField(max_length=100)),
                ('Tweet_URL', models.CharField(max_length=100)),
            ],
        ),
    ]
