# Generated by Django 3.2.18 on 2023-05-19 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 5, 46, 167346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 5, 46, 166452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status_scraping',
            field=models.CharField(default='d_settings', max_length=20),
        ),
    ]
