# Generated by Django 3.2.18 on 2023-05-24 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20230519_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status_scraping',
            new_name='StatusSc',
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 9, 5, 16, 162962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 9, 5, 16, 161960, tzinfo=utc)),
        ),
    ]
