# Generated by Django 3.2.18 on 2023-05-24 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_auto_20230524_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='StatusSc',
            new_name='status_scraping',
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 9, 12, 4, 862204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 9, 12, 4, 861244, tzinfo=utc)),
        ),
    ]
