# Generated by Django 3.2.16 on 2023-04-19 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_auto_20230419_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_settings',
            old_name='C_Id',
            new_name='Primary_key',
        ),
        migrations.RenameField(
            model_name='d_settings',
            old_name='D_Id',
            new_name='Primary_key',
        ),
        migrations.RenameField(
            model_name='result_output',
            old_name='R_Id',
            new_name='Primary_key',
        ),
        migrations.AddField(
            model_name='c_settings',
            name='C_unique_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='d_settings',
            name='D_uniq_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='result_output',
            name='R_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 3, 47, 55138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 3, 46, 986949, tzinfo=utc)),
        ),
    ]
