# Generated by Django 3.2.18 on 2023-05-24 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_auto_20230524_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_settings',
            name='words',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 3, 13, 880869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 3, 13, 879973, tzinfo=utc)),
        ),
    ]
