# Generated by Django 3.2.16 on 2023-04-19 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0006_auto_20230419_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='geocode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minlikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minreplies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minretweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='proximity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='proxy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='resume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 10, 43, 43184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='geocode',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='minlikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='minreplies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='minretweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='proximity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='proxy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='resume',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 10, 42, 973875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Embedded_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Emojis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Imag_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Retweets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result_output',
            name='Tweet_URL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
