# Generated by Django 3.2.18 on 2023-05-24 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0006_auto_20230524_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='display_type',
            field=models.CharField(default='Top', max_length=30),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='from_account',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='geocode',
            field=models.CharField(default='-5.93075788869572, 35.890266339859565', max_length=100),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='hashtag',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='interval',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='mention_account',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minlikes',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minreplies',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='minretweets',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='proximity',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='proxy',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='resume',
            field=models.CharField(default=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 32, 5, 467543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='to_account',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='words',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='geocode',
            field=models.CharField(default='-5.93075788869572, 35.890266339859565', max_length=80),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='proximity',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 32, 5, 466635, tzinfo=utc)),
        ),
    ]
