# Generated by Django 3.2.18 on 2023-05-24 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0007_auto_20230524_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 32, 38, 635932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 10, 32, 38, 635013, tzinfo=utc)),
        ),
    ]
