# Generated by Django 3.2.18 on 2023-05-25 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0008_auto_20230524_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='hashtag',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 42, 5, 982872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 42, 5, 982008, tzinfo=utc)),
        ),
    ]
