# Generated by Django 3.2.18 on 2023-05-25 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0010_auto_20230525_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='resume',
            field=models.CharField(default=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 0, 9, 647673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 0, 9, 646585, tzinfo=utc)),
        ),
    ]
