# Generated by Django 3.2.18 on 2023-05-25 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0012_auto_20230525_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 8, 37, 911610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 15, 8, 37, 910578, tzinfo=utc)),
        ),
    ]
