# Generated by Django 3.2.18 on 2023-05-30 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0013_auto_20230525_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status_scraping',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statusS',
            field=models.CharField(default='d_settings', max_length=20),
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 11, 40, 26, 316737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 11, 40, 26, 315716, tzinfo=utc)),
        ),
    ]
