# Generated by Django 3.2.18 on 2023-05-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0015_auto_20230512_1941'),
    ]

    operations = [
    ]
