# Generated by Django 3.2.16 on 2023-04-19 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20230419_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 10, 50, 16, 645466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 10, 50, 16, 577881, tzinfo=utc)),
        ),
    ]
