# Generated by Django 3.2.18 on 2023-05-10 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0011_auto_20230510_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 19, 48, 16, 127859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 19, 48, 16, 127083, tzinfo=utc)),
        ),
    ]
