# Generated by Django 3.2.18 on 2023-05-13 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0016_auto_20230512_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_settings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='d_settings',
            name='id',
        ),
        migrations.AddField(
            model_name='c_settings',
            name='Primary_key',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d_settings',
            name='Primary_key',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='c_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 8, 39, 48, 164327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_settings',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 8, 39, 48, 163468, tzinfo=utc)),
        ),
    ]
